spring:
  application:
    name: restaurant-service
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 500000 # 5 minutes in milliseconds
      key-prefix: "quickbite:"
      use-key-prefix: true
      cache-null-values: false
  datasource:
    url: jdbc:postgresql://localhost:5433/quickbite-restaurant
    username: quickbite
    password: quickbite
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: restaurant-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.devalere.quickbite.*"

      # ============================================
      # FLYWAY
      # ============================================
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # ============================================
  # SECURITE OAuth2 (JWT Keycloak)
  # ============================================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/quickbite

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info

      # ============================================
      # GRPC
      # ============================================
grpc:
  server:
    port: 9001

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE